### ISSUE TITLE
French TCGdex

### ISSUE THREAD

**Issue by Kiira666999** [tcgdex/python-sdk#1]
Hello I tried to setup the TCGdex as followed : tcgdex = TCGdex('fr') or tcgdex = TCGdex('Language.FR')

But everything returned is in english I dont know if thats an issue or just not implemented

**Comment by Aviortheking** [comment]
Hey, thanks for the report !

I am publishing a fix right now

**Comment by Aviortheking** [comment]
it should be no fixed in the `2.0.1` version :D
